// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "support@location-microservice.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/batch/reverse-geocode": {
            "post": {
                "description": "Определяет административные адреса для нескольких точек за один запрос (до 100 точек)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Search"
                ],
                "summary": "Пакетное обратное геокодирование",
                "parameters": [
                    {
                        "description": "Массив координат точек",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.BatchReverseGeocodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.BatchReverseGeocodeResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/batch/transport/nearest": {
            "post": {
                "description": "Находит ближайшие станции общественного транспорта для нескольких точек одновременно (до 100 точек за запрос)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transport"
                ],
                "summary": "Пакетный поиск ближайших станций для нескольких точек",
                "parameters": [
                    {
                        "description": "Массив точек и параметры поиска",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.BatchNearestTransportRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.BatchNearestTransportResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/beaches/tiles/{z}/{x}/{y}.pbf": {
            "get": {
                "description": "Возвращает векторный тайл (Mapbox Vector Tile) с пляжами. Минимальный уровень зума: 12.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/vnd.mapbox-vector-tile"
                ],
                "tags": [
                    "Tiles"
                ],
                "summary": "Получение векторного тайла с пляжами",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Zoom level (min: 12, max: 22)",
                        "name": "z",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tile X coordinate",
                        "name": "x",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tile Y coordinate",
                        "name": "y",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Vector tile in PBF format",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Minimum zoom level is 12",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to generate tile",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/boundaries/tiles/{z}/{x}/{y}.pbf": {
            "get": {
                "description": "Возвращает векторный тайл (Mapbox Vector Tile) с административными границами (страны, регионы, провинции, города, районы)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/x-protobuf"
                ],
                "tags": [
                    "Tiles"
                ],
                "summary": "Получение векторного тайла с административными границами",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Zoom level (0-22)",
                        "name": "z",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tile X coordinate",
                        "name": "x",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tile Y coordinate",
                        "name": "y",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Vector tile in PBF format",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "500": {
                        "description": "Failed to generate tile",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/boundaries/{id}": {
            "get": {
                "description": "Возвращает подробную информацию об административной границе по её идентификатору",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Search"
                ],
                "summary": "Получение границы по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID административной границы",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о границе",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/green-spaces/tiles/{z}/{x}/{y}.pbf": {
            "get": {
                "description": "Возвращает векторный тайл (Mapbox Vector Tile) с парками, садами и другими зелеными пространствами",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/x-protobuf"
                ],
                "tags": [
                    "Tiles"
                ],
                "summary": "Получение векторного тайла с зелеными зонами",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Zoom level (0-22)",
                        "name": "z",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tile X coordinate",
                        "name": "x",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tile Y coordinate",
                        "name": "y",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Vector tile in PBF format",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "500": {
                        "description": "Failed to generate tile",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/locations/detect/batch": {
            "post": {
                "description": "Определяет административные границы для пачки локаций без поиска транспорта",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Location Detection"
                ],
                "summary": "Batch детекция локаций (без транспорта)",
                "parameters": [
                    {
                        "description": "Массив локаций для детекции (до 100)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.DetectLocationBatchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.DetectLocationBatchResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/locations/enrich": {
            "post": {
                "description": "Обогащает одну локацию: определяет административные границы и находит ближайший транспорт",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Location Enrichment"
                ],
                "summary": "Обогащение одной локации",
                "parameters": [
                    {
                        "description": "Данные локации",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.EnrichSingleLocationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.EnrichedLocationResult"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/locations/enrich/batch": {
            "post": {
                "description": "Обогащает пачку локаций: определяет административные границы и находит ближайший транспорт для visible локаций",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Location Enrichment"
                ],
                "summary": "Batch обогащение локаций",
                "parameters": [
                    {
                        "description": "Массив локаций для обогащения (до 100)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.EnrichLocationBatchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.EnrichLocationBatchResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/noise-sources/tiles/{z}/{x}/{y}.pbf": {
            "get": {
                "description": "Возвращает векторный тайл (Mapbox Vector Tile) с источниками шума (дороги, железные дороги, аэропорты)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/vnd.mapbox-vector-tile"
                ],
                "tags": [
                    "Tiles"
                ],
                "summary": "Получение векторного тайла с источниками шума",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Zoom level (0-22)",
                        "name": "z",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tile X coordinate",
                        "name": "x",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tile Y coordinate",
                        "name": "y",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Vector tile in PBF format",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "500": {
                        "description": "Failed to generate tile",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/poi/categories": {
            "get": {
                "description": "Возвращает полный список доступных категорий точек интереса (healthcare, shopping, education и т.д.) на указанном языке",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "POI"
                ],
                "summary": "Получение списка категорий POI",
                "parameters": [
                    {
                        "type": "string",
                        "default": "en",
                        "description": "Язык результатов (en, es, ca, ru, uk, fr, pt, it, de)",
                        "name": "language",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": true
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/poi/categories/{id}/subcategories": {
            "get": {
                "description": "Возвращает список подкатегорий для указанной категории POI (например, для healthcare: pharmacy, hospital, clinic)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "POI"
                ],
                "summary": "Получение подкатегорий для категории",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID категории",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "en",
                        "description": "Язык результатов (en, es, ca, ru, uk, fr, pt, it, de)",
                        "name": "language",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": true
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/radius/poi": {
            "post": {
                "description": "Находит точки интереса (магазины, рестораны, больницы и т.д.) в указанном радиусе от точки. Поддерживает фильтрацию по категориям.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "POI"
                ],
                "summary": "Поиск точек интереса (POI) в радиусе",
                "parameters": [
                    {
                        "description": "Параметры поиска POI",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.RadiusPOIRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.RadiusPOIResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/radius/tiles.pbf": {
            "post": {
                "description": "Возвращает векторный тайл (Mapbox Vector Tile) со всеми типами данных в указанном радиусе от точки: границы, транспорт, POI, зеленые зоны, воду и т.д. Можно фильтровать слои через параметр layers.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/vnd.mapbox-vector-tile"
                ],
                "tags": [
                    "Tiles"
                ],
                "summary": "Получение всех данных в радиусе в формате векторного тайла",
                "parameters": [
                    {
                        "description": "Координаты центра, радиус и опциональный список слоев",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.RadiusTilesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Vector tile in PBF format",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to generate tile",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/reverse-geocode": {
            "post": {
                "description": "Определяет административный адрес (страна, регион, провинция, город, район) по географическим координатам",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Search"
                ],
                "summary": "Обратное геокодирование",
                "parameters": [
                    {
                        "description": "Координаты точки",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.ReverseGeocodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.ReverseGeocodeResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/search": {
            "get": {
                "description": "Выполняет полнотекстовый поиск по административным границам (страны, регионы, города, районы). Поддерживает поиск на разных языках и фильтрацию по административным уровням.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Search"
                ],
                "summary": "Поиск административных границ по тексту",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Поисковый запрос (минимум 2 символа)",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "en",
                        "description": "Язык результатов (en, es, ca, ru, uk, fr, pt, it, de)",
                        "name": "language",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Максимальное количество результатов",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.SearchResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/stats": {
            "get": {
                "description": "Возвращает агрегированную статистику по всем данным в системе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Statistics"
                ],
                "summary": "Get system statistics",
                "responses": {
                    "200": {
                        "description": "Статистика системы",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/tiles/poi/{z}/{x}/{y}.pbf": {
            "get": {
                "description": "Возвращает векторный тайл (Mapbox Vector Tile) с точками интереса. Поддерживает фильтрацию по категориям и подкатегориям через query параметры.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/x-protobuf"
                ],
                "tags": [
                    "POI Tiles"
                ],
                "summary": "Получение векторного тайла с POI",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Zoom level (0-22)",
                        "name": "z",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tile X coordinate",
                        "name": "x",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tile Y coordinate",
                        "name": "y",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Категории через запятую (healthcare,shopping,education)",
                        "name": "categories",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Подкатегории через запятую (pharmacy,hospital,school)",
                        "name": "subcategories",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Vector tile in PBF format",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/tiles/transport/{z}/{x}/{y}.pbf": {
            "get": {
                "description": "Возвращает векторный тайл (Mapbox Vector Tile) с транспортными станциями, отфильтрованными по типам. Поддерживает фильтрацию по metro, bus, tram, train.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/x-protobuf"
                ],
                "tags": [
                    "Transport Tiles"
                ],
                "summary": "Получение векторного тайла с транспортом по типам",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Zoom level (0-22)",
                        "name": "z",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tile X coordinate",
                        "name": "x",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tile Y coordinate",
                        "name": "y",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Типы транспорта через запятую (metro,bus,tram,train)",
                        "name": "types",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Vector tile in PBF format",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/tourist-zones/tiles/{z}/{x}/{y}.pbf": {
            "get": {
                "description": "Возвращает векторный тайл (Mapbox Vector Tile) с туристическими зонами и достопримечательностями. Минимальный уровень зума: 11.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/vnd.mapbox-vector-tile"
                ],
                "tags": [
                    "Tiles"
                ],
                "summary": "Получение векторного тайла с туристическими зонами",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Zoom level (min: 11, max: 22)",
                        "name": "z",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tile X coordinate",
                        "name": "x",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tile Y coordinate",
                        "name": "y",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Vector tile in PBF format",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Minimum zoom level is 11",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to generate tile",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/transport/lines.pbf": {
            "post": {
                "description": "Возвращает векторный тайл (Mapbox Vector Tile) с геометрией и станциями нескольких транспортных линий (до 50 линий за запрос)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/vnd.mapbox-vector-tile"
                ],
                "tags": [
                    "Transport Tiles"
                ],
                "summary": "Получение векторного тайла для нескольких транспортных линий",
                "parameters": [
                    {
                        "description": "Массив ID линий",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.TransportLinesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Vector tile in PBF format",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Invalid request or too many IDs",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to generate tile",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/transport/lines/{id}.pbf": {
            "get": {
                "description": "Возвращает векторный тайл (Mapbox Vector Tile) с геометрией и станциями указанной транспортной линии",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/vnd.mapbox-vector-tile"
                ],
                "tags": [
                    "Transport Tiles"
                ],
                "summary": "Получение векторного тайла для одной транспортной линии",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID транспортной линии",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Vector tile in PBF format",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Invalid line ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to generate tile",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/transport/nearest": {
            "post": {
                "description": "Находит ближайшие станции общественного транспорта (метро, автобусы, трамваи, поезда) в указанном радиусе от точки. Возвращает информацию о станциях и проходящих через них линиях.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transport"
                ],
                "summary": "Поиск ближайших станций транспорта",
                "parameters": [
                    {
                        "description": "Параметры поиска станций",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.NearestTransportRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.NearestTransportResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/transport/priority": {
            "get": {
                "description": "Находит ближайший транспорт с приоритетом (metro/train → bus/tram)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transport"
                ],
                "summary": "Поиск ближайшего транспорта с приоритетом",
                "parameters": [
                    {
                        "type": "number",
                        "description": "Широта",
                        "name": "lat",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Долгота",
                        "name": "lon",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "default": 1500,
                        "description": "Радиус поиска в метрах",
                        "name": "radius",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 5,
                        "description": "Максимальное количество станций",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.PriorityTransportResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/transport/priority/batch": {
            "post": {
                "description": "Находит ближайший транспорт для нескольких точек одним запросом",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transport"
                ],
                "summary": "Batch поиск ближайшего транспорта с приоритетом",
                "parameters": [
                    {
                        "description": "Массив точек",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.PriorityTransportBatchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.PriorityTransportBatchResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/transport/station/{station_id}/lines": {
            "get": {
                "description": "Возвращает список транспортных линий, которые проходят через указанную станцию (с информацией о цветах, операторах и т.д.)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transport"
                ],
                "summary": "Получение линий для станции",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID станции",
                        "name": "station_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список линий транспорта",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/transport/tiles/{z}/{x}/{y}.pbf": {
            "get": {
                "description": "Возвращает векторный тайл (Mapbox Vector Tile) со всеми транспортными станциями и линиями без фильтрации",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/x-protobuf"
                ],
                "tags": [
                    "Tiles"
                ],
                "summary": "Получение векторного тайла с транспортом",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Zoom level (0-22)",
                        "name": "z",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tile X coordinate",
                        "name": "x",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tile Y coordinate",
                        "name": "y",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Vector tile in PBF format",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "500": {
                        "description": "Failed to generate tile",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/water/tiles/{z}/{x}/{y}.pbf": {
            "get": {
                "description": "Возвращает векторный тайл (Mapbox Vector Tile) с реками, озерами, морями и другими водными объектами",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/vnd.mapbox-vector-tile"
                ],
                "tags": [
                    "Tiles"
                ],
                "summary": "Получение векторного тайла с водными объектами",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Zoom level (0-22)",
                        "name": "z",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tile X coordinate",
                        "name": "x",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tile Y coordinate",
                        "name": "y",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Vector tile in PBF format",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "500": {
                        "description": "Failed to generate tile",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_location-microservice_internal_domain.Address": {
            "type": "object",
            "properties": {
                "city": {
                    "description": "admin_level 8",
                    "type": "string"
                },
                "country": {
                    "description": "admin_level 2",
                    "type": "string"
                },
                "district": {
                    "description": "admin_level 9",
                    "type": "string"
                },
                "neighborhood": {
                    "description": "admin_level 11",
                    "type": "string"
                },
                "province": {
                    "description": "admin_level 6",
                    "type": "string"
                },
                "region": {
                    "description": "admin_level 4",
                    "type": "string"
                },
                "subdistrict": {
                    "description": "admin_level 10",
                    "type": "string"
                },
                "subprovince": {
                    "description": "admin_level 7",
                    "type": "string"
                }
            }
        },
        "github_com_location-microservice_internal_pkg_errors.AppError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": true
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_location-microservice_internal_pkg_utils.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_location-microservice_internal_pkg_errors.AppError"
                }
            }
        },
        "github_com_location-microservice_internal_pkg_utils.Meta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "time_ms": {
                    "type": "number"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_location-microservice_internal_pkg_utils.SuccessResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "meta": {
                    "$ref": "#/definitions/github_com_location-microservice_internal_pkg_utils.Meta"
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.BatchNearestTransportRequest": {
            "type": "object",
            "required": [
                "points",
                "types"
            ],
            "properties": {
                "max_distance": {
                    "description": "meters",
                    "type": "number",
                    "maximum": 10000,
                    "minimum": 100
                },
                "points": {
                    "type": "array",
                    "maxItems": 100,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.Point"
                    }
                },
                "types": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.BatchNearestTransportResponse": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.TransportStationWithLines"
                        }
                    }
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.BatchReverseGeocodeRequest": {
            "type": "object",
            "required": [
                "points"
            ],
            "properties": {
                "points": {
                    "type": "array",
                    "maxItems": 100,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.Point"
                    }
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.BatchReverseGeocodeResponse": {
            "type": "object",
            "properties": {
                "addresses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_location-microservice_internal_domain.Address"
                    }
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.BoundaryInfoDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "translate_names": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.DetectLocationBatchRequest": {
            "type": "object",
            "required": [
                "locations"
            ],
            "properties": {
                "locations": {
                    "type": "array",
                    "maxItems": 100,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.LocationInput"
                    }
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.DetectLocationBatchResponse": {
            "type": "object",
            "properties": {
                "meta": {
                    "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.LocationBatchMeta"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.LocationDetectionResult"
                    }
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.EnrichLocationBatchMeta": {
            "type": "object",
            "properties": {
                "error_count": {
                    "type": "integer"
                },
                "success_count": {
                    "type": "integer"
                },
                "total_locations": {
                    "type": "integer"
                },
                "with_transport": {
                    "description": "кол-во локаций с транспортом",
                    "type": "integer"
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.EnrichLocationBatchRequest": {
            "type": "object",
            "required": [
                "locations"
            ],
            "properties": {
                "locations": {
                    "type": "array",
                    "maxItems": 100,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.LocationInput"
                    }
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.EnrichLocationBatchResponse": {
            "type": "object",
            "properties": {
                "meta": {
                    "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.EnrichLocationBatchMeta"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.EnrichedLocationResult"
                    }
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.EnrichSingleLocationRequest": {
            "type": "object",
            "required": [
                "country"
            ],
            "properties": {
                "city": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "is_visible": {
                    "type": "boolean"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "neighborhood": {
                    "type": "string"
                },
                "province": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.EnrichedLocationDTO": {
            "type": "object",
            "properties": {
                "city": {
                    "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.BoundaryInfoDTO"
                },
                "country": {
                    "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.BoundaryInfoDTO"
                },
                "district": {
                    "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.BoundaryInfoDTO"
                },
                "is_address_visible": {
                    "type": "boolean"
                },
                "neighborhood": {
                    "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.BoundaryInfoDTO"
                },
                "province": {
                    "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.BoundaryInfoDTO"
                },
                "region": {
                    "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.BoundaryInfoDTO"
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.EnrichedLocationResult": {
            "type": "object",
            "properties": {
                "enriched_location": {
                    "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.EnrichedLocationDTO"
                },
                "error": {
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                },
                "nearest_transport": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.PriorityTransportStation"
                    }
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.LocationBatchMeta": {
            "type": "object",
            "properties": {
                "db_queries_count": {
                    "description": "количество запросов в БД",
                    "type": "integer"
                },
                "error_count": {
                    "type": "integer"
                },
                "name_resolve_count": {
                    "description": "обработано по названиям",
                    "type": "integer"
                },
                "success_count": {
                    "type": "integer"
                },
                "total_locations": {
                    "type": "integer"
                },
                "visible_count": {
                    "description": "обработано по координатам",
                    "type": "integer"
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.LocationDetectionResult": {
            "type": "object",
            "properties": {
                "enriched_location": {
                    "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.EnrichedLocationDTO"
                },
                "error": {
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.LocationInput": {
            "type": "object",
            "required": [
                "country"
            ],
            "properties": {
                "city": {
                    "description": "город",
                    "type": "string"
                },
                "country": {
                    "description": "страна (обязательно)",
                    "type": "string",
                    "minLength": 2
                },
                "district": {
                    "description": "район",
                    "type": "string"
                },
                "house_number": {
                    "description": "номер дома",
                    "type": "string"
                },
                "index": {
                    "description": "индекс для маппинга результатов",
                    "type": "integer"
                },
                "is_visible": {
                    "description": "флаг видимости адреса",
                    "type": "boolean"
                },
                "latitude": {
                    "type": "number",
                    "maximum": 90,
                    "minimum": -90
                },
                "longitude": {
                    "type": "number",
                    "maximum": 180,
                    "minimum": -180
                },
                "neighborhood": {
                    "description": "квартал",
                    "type": "string"
                },
                "province": {
                    "description": "провинция",
                    "type": "string"
                },
                "region": {
                    "description": "регион",
                    "type": "string"
                },
                "street": {
                    "description": "улица",
                    "type": "string"
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.NearestTransportRequest": {
            "type": "object",
            "required": [
                "lat",
                "lon",
                "types"
            ],
            "properties": {
                "lat": {
                    "type": "number",
                    "maximum": 90,
                    "minimum": -90
                },
                "lon": {
                    "type": "number",
                    "maximum": 180,
                    "minimum": -180
                },
                "max_distance": {
                    "description": "meters",
                    "type": "number",
                    "maximum": 10000,
                    "minimum": 100
                },
                "types": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.NearestTransportResponse": {
            "type": "object",
            "properties": {
                "stations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.TransportStationWithLines"
                    }
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.POISimple": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "distance": {
                    "description": "meters",
                    "type": "number"
                },
                "id": {
                    "description": "Converted to string for frontend",
                    "type": "string"
                },
                "lat": {
                    "type": "number"
                },
                "lon": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "subcategory": {
                    "type": "string"
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.Point": {
            "type": "object",
            "required": [
                "lat",
                "lon"
            ],
            "properties": {
                "lat": {
                    "type": "number",
                    "maximum": 90,
                    "minimum": -90
                },
                "lon": {
                    "type": "number",
                    "maximum": 180,
                    "minimum": -180
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.PriorityTransportBatchMeta": {
            "type": "object",
            "properties": {
                "radius_m": {
                    "type": "number"
                },
                "total_points": {
                    "type": "integer"
                },
                "total_stations": {
                    "type": "integer"
                },
                "walking_speed_kmh": {
                    "type": "number"
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.PriorityTransportBatchRequest": {
            "type": "object",
            "required": [
                "points"
            ],
            "properties": {
                "limit": {
                    "description": "лимит на точку",
                    "type": "integer",
                    "maximum": 10,
                    "minimum": 1
                },
                "points": {
                    "type": "array",
                    "maxItems": 100,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.PriorityTransportPoint"
                    }
                },
                "radius": {
                    "description": "метры для всех точек",
                    "type": "number",
                    "maximum": 10000,
                    "minimum": 100
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.PriorityTransportBatchResponse": {
            "type": "object",
            "properties": {
                "meta": {
                    "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.PriorityTransportBatchMeta"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.PriorityTransportPointResult"
                    }
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.PriorityTransportMeta": {
            "type": "object",
            "properties": {
                "has_high_priority": {
                    "description": "есть ли metro/train в радиусе",
                    "type": "boolean"
                },
                "priority_type": {
                    "description": "\"metro/train\" или \"bus/tram\"",
                    "type": "string"
                },
                "radius_m": {
                    "type": "number"
                },
                "search_point": {
                    "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.Point"
                },
                "total_found": {
                    "type": "integer"
                },
                "walking_speed_kmh": {
                    "description": "скорость ходьбы для расчёта",
                    "type": "number"
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.PriorityTransportPoint": {
            "type": "object",
            "required": [
                "lat",
                "lon"
            ],
            "properties": {
                "lat": {
                    "type": "number",
                    "maximum": 90,
                    "minimum": -90
                },
                "lon": {
                    "type": "number",
                    "maximum": 180,
                    "minimum": -180
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.PriorityTransportPointResult": {
            "type": "object",
            "properties": {
                "point_index": {
                    "type": "integer"
                },
                "search_point": {
                    "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.Point"
                },
                "stations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.PriorityTransportStation"
                    }
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.PriorityTransportResponse": {
            "type": "object",
            "properties": {
                "meta": {
                    "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.PriorityTransportMeta"
                },
                "stations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.PriorityTransportStation"
                    }
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.PriorityTransportStation": {
            "type": "object",
            "properties": {
                "lat": {
                    "type": "number"
                },
                "linear_distance": {
                    "description": "метры",
                    "type": "number"
                },
                "lines": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.TransportLineInfoEnriched"
                    }
                },
                "lon": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "name_en": {
                    "type": "string"
                },
                "station_id": {
                    "type": "integer"
                },
                "type": {
                    "description": "metro, train, tram, bus",
                    "type": "string"
                },
                "walking_distance": {
                    "description": "метры (примерно)",
                    "type": "number"
                },
                "walking_time": {
                    "description": "минуты",
                    "type": "number"
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.RadiusPOIRequest": {
            "type": "object",
            "required": [
                "lat",
                "lon",
                "radius_km"
            ],
            "properties": {
                "categories": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "lat": {
                    "type": "number",
                    "maximum": 90,
                    "minimum": -90
                },
                "limit": {
                    "type": "integer",
                    "maximum": 500,
                    "minimum": 1
                },
                "lon": {
                    "type": "number",
                    "maximum": 180,
                    "minimum": -180
                },
                "radius_km": {
                    "type": "number",
                    "maximum": 100,
                    "minimum": 0.1
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.RadiusPOIResponse": {
            "type": "object",
            "properties": {
                "pois": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.POISimple"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.RadiusTilesRequest": {
            "type": "object",
            "required": [
                "lat",
                "lon",
                "radius_km"
            ],
            "properties": {
                "lat": {
                    "type": "number",
                    "maximum": 90,
                    "minimum": -90
                },
                "layers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "lon": {
                    "type": "number",
                    "maximum": 180,
                    "minimum": -180
                },
                "radius_km": {
                    "type": "number",
                    "maximum": 50,
                    "minimum": 0.1
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.ReverseGeocodeRequest": {
            "type": "object",
            "required": [
                "lat",
                "lon"
            ],
            "properties": {
                "lat": {
                    "type": "number",
                    "maximum": 90,
                    "minimum": -90
                },
                "lon": {
                    "type": "number",
                    "maximum": 180,
                    "minimum": -180
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.ReverseGeocodeResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "$ref": "#/definitions/github_com_location-microservice_internal_domain.Address"
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.SearchResponse": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.SearchResult"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.SearchResult": {
            "type": "object",
            "properties": {
                "admin_level": {
                    "type": "integer"
                },
                "area_sq_km": {
                    "type": "number"
                },
                "center_lat": {
                    "type": "number"
                },
                "center_lon": {
                    "type": "number"
                },
                "id": {
                    "description": "Converted to string for frontend",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.TransportLineInfoEnriched": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "ref": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.TransportLineSimple": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "id": {
                    "description": "Converted to string for frontend",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "ref": {
                    "type": "string"
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.TransportLinesRequest": {
            "type": "object",
            "required": [
                "ids"
            ],
            "properties": {
                "ids": {
                    "type": "array",
                    "maxItems": 50,
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_location-microservice_internal_usecase_dto.TransportStationWithLines": {
            "type": "object",
            "properties": {
                "distance": {
                    "description": "meters",
                    "type": "number"
                },
                "id": {
                    "description": "Converted to string for frontend",
                    "type": "string"
                },
                "lat": {
                    "type": "number"
                },
                "lines": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_location-microservice_internal_usecase_dto.TransportLineSimple"
                    }
                },
                "lon": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Location Microservice API",
	Description:      "Микросервис для работы с геопространственными данными из OpenStreetMap. Предоставляет API для поиска административных границ, транспортной инфраструктуры, точек интереса (POI), а также векторных тайлов для визуализации на картах.\n\nОсновные возможности:\n- Поиск и обратное геокодирование административных границ\n- Поиск ближайших транспортных станций (метро, автобусы, трамваи)\n- Поиск точек интереса по категориям в радиусе\n- Получение векторных тайлов (MVT/PBF) для всех типов данных\n- Статистика по загруженным данным",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
