-- Откат изменений: возврат к исходным размерам полей

-- Откат изменений типа геометрии beaches
ALTER TABLE beaches ALTER COLUMN geometry TYPE GEOMETRY(POLYGON, 4326);

ALTER TABLE pois ALTER COLUMN brand TYPE VARCHAR(100);
ALTER TABLE pois ALTER COLUMN operator TYPE VARCHAR(100);
ALTER TABLE pois ALTER COLUMN cuisine TYPE VARCHAR(100);
ALTER TABLE pois ALTER COLUMN charge TYPE VARCHAR(100);

ALTER TABLE pois ALTER COLUMN phone TYPE VARCHAR(50);
ALTER TABLE pois ALTER COLUMN diet TYPE VARCHAR(50);
ALTER TABLE pois ALTER COLUMN internet TYPE VARCHAR(50);
ALTER TABLE pois ALTER COLUMN smoking TYPE VARCHAR(50);
