DROP TABLE IF EXISTS transport_lines CASCADE;
DROP TABLE IF EXISTS transport_stations CASCADE;
DROP TABLE IF EXISTS admin_boundaries CASCADE;

DROP EXTENSION IF EXISTS "uuid-ossp";
DROP EXTENSION IF EXISTS pg_trgm;
DROP EXTENSION IF EXISTS fuzzystrmatch;
DROP EXTENSION IF EXISTS postgis_topology;
DROP EXTENSION IF EXISTS postgis;
