-- Откат расширенных полей для POI
-- Удаление индексов
DROP INDEX IF EXISTS idx_pois_delivery;
DROP INDEX IF EXISTS idx_pois_takeaway;
DROP INDEX IF EXISTS idx_pois_outdoor_seating;
DROP INDEX IF EXISTS idx_pois_wheelchair_access;
DROP INDEX IF EXISTS idx_pois_stars;
DROP INDEX IF EXISTS idx_pois_diet;
DROP INDEX IF EXISTS idx_pois_cuisine;
DROP INDEX IF EXISTS idx_pois_brand;

-- Удаление колонок
ALTER TABLE pois DROP COLUMN IF EXISTS wikipedia;
ALTER TABLE pois DROP COLUMN IF EXISTS wikidata;
ALTER TABLE pois DROP COLUMN IF EXISTS image_url;

ALTER TABLE pois DROP COLUMN IF EXISTS twitter;
ALTER TABLE pois DROP COLUMN IF EXISTS instagram;
ALTER TABLE pois DROP COLUMN IF EXISTS facebook;

ALTER TABLE pois DROP COLUMN IF EXISTS payment_cards;
ALTER TABLE pois DROP COLUMN IF EXISTS payment_cash;
ALTER TABLE pois DROP COLUMN IF EXISTS charge;
ALTER TABLE pois DROP COLUMN IF EXISTS fee;

ALTER TABLE pois DROP COLUMN IF EXISTS drive_through;
ALTER TABLE pois DROP COLUMN IF EXISTS delivery;
ALTER TABLE pois DROP COLUMN IF EXISTS takeaway;
ALTER TABLE pois DROP COLUMN IF EXISTS outdoor_seating;
ALTER TABLE pois DROP COLUMN IF EXISTS smoking;
ALTER TABLE pois DROP COLUMN IF EXISTS internet_fee;
ALTER TABLE pois DROP COLUMN IF EXISTS internet;

ALTER TABLE pois DROP COLUMN IF EXISTS min_age;
ALTER TABLE pois DROP COLUMN IF EXISTS capacity;
ALTER TABLE pois DROP COLUMN IF EXISTS beds;
ALTER TABLE pois DROP COLUMN IF EXISTS rooms;
ALTER TABLE pois DROP COLUMN IF EXISTS stars;

ALTER TABLE pois DROP COLUMN IF EXISTS diet;
ALTER TABLE pois DROP COLUMN IF EXISTS cuisine;
ALTER TABLE pois DROP COLUMN IF EXISTS operator;
ALTER TABLE pois DROP COLUMN IF EXISTS brand;
ALTER TABLE pois DROP COLUMN IF EXISTS description;

ALTER TABLE pois DROP COLUMN IF EXISTS email;
